/**
 * MFE-03/05 — Catálogo oficial de eventos financeiros
 */

const OfficialFinancialEventTypes = Object.freeze({
  SALE_COMPLETED: 'SALE_COMPLETED',
  SALE_CANCELLED: 'SALE_CANCELLED',
  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
  PAYMENT_CANCELLED: 'PAYMENT_CANCELLED',
  PURCHASE_CONFIRMED: 'PURCHASE_CONFIRMED',
  PURCHASE_CANCELLED: 'PURCHASE_CANCELLED',
  ACCOUNT_RECEIVABLE_CREATED: 'ACCOUNT_RECEIVABLE_CREATED',
  ACCOUNT_RECEIVABLE_UPDATED: 'ACCOUNT_RECEIVABLE_UPDATED',
  ACCOUNT_RECEIVABLE_CANCELLED: 'ACCOUNT_RECEIVABLE_CANCELLED',
  ACCOUNT_RECEIVABLE_SETTLED: 'ACCOUNT_RECEIVABLE_SETTLED',
  ACCOUNT_RECEIVABLE_PARTIAL: 'ACCOUNT_RECEIVABLE_PARTIAL',
  ACCOUNT_RECEIVABLE_OVERDUE: 'ACCOUNT_RECEIVABLE_OVERDUE',
  ACCOUNT_RECEIVABLE_RENEGOTIATED: 'ACCOUNT_RECEIVABLE_RENEGOTIATED',
  ACCOUNT_PAYABLE_CREATED: 'ACCOUNT_PAYABLE_CREATED',
  ACCOUNT_PAYABLE_UPDATED: 'ACCOUNT_PAYABLE_UPDATED',
  ACCOUNT_PAYABLE_CANCELLED: 'ACCOUNT_PAYABLE_CANCELLED',
  ACCOUNT_PAYABLE_SETTLED: 'ACCOUNT_PAYABLE_SETTLED',
  ACCOUNT_PAYABLE_PARTIAL: 'ACCOUNT_PAYABLE_PARTIAL',
  ACCOUNT_PAYABLE_OVERDUE: 'ACCOUNT_PAYABLE_OVERDUE',
  ACCOUNT_PAYABLE_RENEGOTIATED: 'ACCOUNT_PAYABLE_RENEGOTIATED',
  PIX_RECEIVED: 'PIX_RECEIVED',
  PIX_SENT: 'PIX_SENT',
  TEF_APPROVED: 'TEF_APPROVED',
  TEF_CANCELLED: 'TEF_CANCELLED',
  CASH_OPENED: 'CASH_OPENED',
  CASH_CLOSED: 'CASH_CLOSED',
  CASH_SUPPLY: 'CASH_SUPPLY',
  CASH_WITHDRAWAL: 'CASH_WITHDRAWAL',
  CASH_ADJUSTMENT: 'CASH_ADJUSTMENT',
  CASH_RECONCILIATION: 'CASH_RECONCILIATION',
  STOCK_ADJUSTMENT_FINANCIAL: 'STOCK_ADJUSTMENT_FINANCIAL',
  COMMERCIAL_CREDIT_GENERATED: 'COMMERCIAL_CREDIT_GENERATED',
  COMMERCIAL_CREDIT_USED: 'COMMERCIAL_CREDIT_USED',
  /** MFE-07 — Liquidação */
  PAYMENT_SETTLED: 'PAYMENT_SETTLED',
  PIX_SETTLED: 'PIX_SETTLED',
  TEF_SETTLED: 'TEF_SETTLED',
  CASH_SETTLED: 'CASH_SETTLED',
  CARD_SETTLED: 'CARD_SETTLED',
  CHECK_SETTLED: 'CHECK_SETTLED',
  BANK_TRANSFER_SETTLED: 'BANK_TRANSFER_SETTLED',
  BOLETO_SETTLED: 'BOLETO_SETTLED',
  PAYMENT_REVERSED: 'PAYMENT_REVERSED',
  PAYMENT_FAILED: 'PAYMENT_FAILED'
});

const LegacyFinancialEventTypes = Object.freeze({
  VENDA_RECEBIDA: 'VENDA_RECEBIDA',
  VENDA_CANCELADA: 'VENDA_CANCELADA',
  TITULO_AR_CRIADO: 'TITULO_AR_CRIADO',
  TITULO_AR_ATUALIZADO: 'TITULO_AR_ATUALIZADO',
  TITULO_AR_CANCELADO: 'TITULO_AR_CANCELADO',
  TITULO_AR_BAIXADO: 'TITULO_AR_BAIXADO',
  TITULO_AR_PARCIAL: 'TITULO_AR_PARCIAL',
  TITULO_AR_VENCIDO: 'TITULO_AR_VENCIDO',
  TITULO_AR_RENEGOCIADO: 'TITULO_AR_RENEGOCIADO',
  TITULO_AP_CRIADO: 'TITULO_AP_CRIADO',
  TITULO_AP_ATUALIZADO: 'TITULO_AP_ATUALIZADO',
  TITULO_AP_CANCELADO: 'TITULO_AP_CANCELADO',
  TITULO_AP_BAIXADO: 'TITULO_AP_BAIXADO',
  TITULO_AP_PARCIAL: 'TITULO_AP_PARCIAL',
  TITULO_AP_VENCIDO: 'TITULO_AP_VENCIDO',
  TITULO_AP_RENEGOCIADO: 'TITULO_AP_RENEGOCIADO',
  CAIXA_ABERTO: 'CAIXA_ABERTO',
  CAIXA_FECHADO: 'CAIXA_FECHADO',
  CAIXA_SANGRIA: 'CAIXA_SANGRIA',
  CAIXA_SUPRIMENTO: 'CAIXA_SUPRIMENTO',
  CAIXA_AJUSTE: 'CAIXA_AJUSTE',
  CAIXA_CONCILIACAO: 'CAIXA_CONCILIACAO',
  PIX_RECEBIDO: 'PIX_RECEBIDO',
  PIX_ESTORNADO: 'PIX_ESTORNADO',
  TEF_APROVADO: 'TEF_APROVADO',
  TEF_CANCELADO: 'TEF_CANCELADO',
  TRANSFERENCIA_BANCARIA: 'TRANSFERENCIA_BANCARIA',
  AJUSTE_FINANCEIRO: 'AJUSTE_FINANCEIRO',
  CONCILIACAO_REALIZADA: 'CONCILIACAO_REALIZADA',
  ESTORNO_FINANCEIRO: 'ESTORNO_FINANCEIRO',
  PRESTACAO_RECEBIDA: 'PRESTACAO_RECEBIDA',
  /** MFE-07 — aliases PT liquidação */
  LIQUIDACAO_REALIZADA: 'LIQUIDACAO_REALIZADA',
  PIX_LIQUIDADO: 'PIX_LIQUIDADO',
  TEF_LIQUIDADO: 'TEF_LIQUIDADO',
  DINHEIRO_LIQUIDADO: 'DINHEIRO_LIQUIDADO',
  CARTAO_LIQUIDADO: 'CARTAO_LIQUIDADO',
  CHEQUE_LIQUIDADO: 'CHEQUE_LIQUIDADO',
  TRANSFERENCIA_LIQUIDADA: 'TRANSFERENCIA_LIQUIDADA',
  BOLETO_LIQUIDADO: 'BOLETO_LIQUIDADO',
  LIQUIDACAO_ESTORNADA: 'LIQUIDACAO_ESTORNADA',
  LIQUIDACAO_FALHOU: 'LIQUIDACAO_FALHOU'
});

const EVENT_ALIAS_TO_LEGACY = Object.freeze({
  SALE_COMPLETED: 'VENDA_RECEBIDA',
  SALE_CANCELLED: 'VENDA_CANCELADA',
  PAYMENT_RECEIVED: 'PRESTACAO_RECEBIDA',
  PAYMENT_CANCELLED: 'ESTORNO_FINANCEIRO',
  PURCHASE_CONFIRMED: 'TITULO_AP_CRIADO',
  PURCHASE_CANCELLED: 'ESTORNO_FINANCEIRO',
  ACCOUNT_RECEIVABLE_CREATED: 'TITULO_AR_CRIADO',
  ACCOUNT_RECEIVABLE_UPDATED: 'TITULO_AR_ATUALIZADO',
  ACCOUNT_RECEIVABLE_CANCELLED: 'TITULO_AR_CANCELADO',
  ACCOUNT_RECEIVABLE_SETTLED: 'TITULO_AR_BAIXADO',
  ACCOUNT_RECEIVABLE_PARTIAL: 'TITULO_AR_PARCIAL',
  ACCOUNT_RECEIVABLE_OVERDUE: 'TITULO_AR_VENCIDO',
  ACCOUNT_RECEIVABLE_RENEGOTIATED: 'TITULO_AR_RENEGOCIADO',
  ACCOUNT_PAYABLE_CREATED: 'TITULO_AP_CRIADO',
  ACCOUNT_PAYABLE_UPDATED: 'TITULO_AP_ATUALIZADO',
  ACCOUNT_PAYABLE_CANCELLED: 'TITULO_AP_CANCELADO',
  ACCOUNT_PAYABLE_SETTLED: 'TITULO_AP_BAIXADO',
  ACCOUNT_PAYABLE_PARTIAL: 'TITULO_AP_PARCIAL',
  ACCOUNT_PAYABLE_OVERDUE: 'TITULO_AP_VENCIDO',
  ACCOUNT_PAYABLE_RENEGOTIATED: 'TITULO_AP_RENEGOCIADO',
  PIX_RECEIVED: 'PIX_RECEBIDO',
  PIX_SENT: 'PIX_ESTORNADO',
  TEF_APPROVED: 'TEF_APROVADO',
  TEF_CANCELLED: 'TEF_CANCELADO',
  CASH_OPENED: 'CAIXA_ABERTO',
  CASH_CLOSED: 'CAIXA_FECHADO',
  CASH_SUPPLY: 'CAIXA_SUPRIMENTO',
  CASH_WITHDRAWAL: 'CAIXA_SANGRIA',
  CASH_ADJUSTMENT: 'CAIXA_AJUSTE',
  CASH_RECONCILIATION: 'CAIXA_CONCILIACAO',
  STOCK_ADJUSTMENT_FINANCIAL: 'AJUSTE_FINANCEIRO',
  COMMERCIAL_CREDIT_GENERATED: 'AJUSTE_FINANCEIRO',
  COMMERCIAL_CREDIT_USED: 'AJUSTE_FINANCEIRO',
  PAYMENT_SETTLED: 'LIQUIDACAO_REALIZADA',
  PIX_SETTLED: 'PIX_LIQUIDADO',
  TEF_SETTLED: 'TEF_LIQUIDADO',
  CASH_SETTLED: 'DINHEIRO_LIQUIDADO',
  CARD_SETTLED: 'CARTAO_LIQUIDADO',
  CHECK_SETTLED: 'CHEQUE_LIQUIDADO',
  BANK_TRANSFER_SETTLED: 'TRANSFERENCIA_LIQUIDADA',
  BOLETO_SETTLED: 'BOLETO_LIQUIDADO',
  PAYMENT_REVERSED: 'LIQUIDACAO_ESTORNADA',
  PAYMENT_FAILED: 'LIQUIDACAO_FALHOU'
});

const CASH_EVENT_TYPES = Object.freeze([
  'CASH_OPENED', 'CASH_CLOSED', 'CASH_SUPPLY', 'CASH_WITHDRAWAL',
  'CASH_ADJUSTMENT', 'CASH_RECONCILIATION',
  'CAIXA_ABERTO', 'CAIXA_FECHADO', 'CAIXA_SANGRIA', 'CAIXA_SUPRIMENTO',
  'CAIXA_AJUSTE', 'CAIXA_CONCILIACAO'
]);

const AR_EVENT_TYPES = Object.freeze([
  'ACCOUNT_RECEIVABLE_CREATED',
  'ACCOUNT_RECEIVABLE_UPDATED',
  'ACCOUNT_RECEIVABLE_CANCELLED',
  'ACCOUNT_RECEIVABLE_SETTLED',
  'ACCOUNT_RECEIVABLE_PARTIAL',
  'ACCOUNT_RECEIVABLE_OVERDUE',
  'ACCOUNT_RECEIVABLE_RENEGOTIATED',
  'TITULO_AR_CRIADO',
  'TITULO_AR_ATUALIZADO',
  'TITULO_AR_CANCELADO',
  'TITULO_AR_BAIXADO',
  'TITULO_AR_PARCIAL',
  'TITULO_AR_VENCIDO',
  'TITULO_AR_RENEGOCIADO'
]);

/** MFE-05.1 — eventos de bridge PDV / Comercial → AR */
const BRIDGE_AR_EVENT_TYPES = Object.freeze([
  'SALE_COMPLETED',
  'SALE_CANCELLED',
  'COMMERCIAL_CREDIT_GENERATED',
  'COMMERCIAL_CREDIT_USED',
  'PAYMENT_RECEIVED',
  'VENDA_RECEBIDA',
  'VENDA_CANCELADA',
  'PRESTACAO_RECEBIDA'
]);

/** MFE-06 — eventos Contas a Pagar / Compras */
const AP_EVENT_TYPES = Object.freeze([
  'ACCOUNT_PAYABLE_CREATED',
  'ACCOUNT_PAYABLE_UPDATED',
  'ACCOUNT_PAYABLE_CANCELLED',
  'ACCOUNT_PAYABLE_SETTLED',
  'ACCOUNT_PAYABLE_PARTIAL',
  'ACCOUNT_PAYABLE_OVERDUE',
  'ACCOUNT_PAYABLE_RENEGOTIATED',
  'TITULO_AP_CRIADO',
  'TITULO_AP_ATUALIZADO',
  'TITULO_AP_CANCELADO',
  'TITULO_AP_BAIXADO',
  'TITULO_AP_PARCIAL',
  'TITULO_AP_VENCIDO',
  'TITULO_AP_RENEGOCIADO'
]);

/** MFE-06 — bridge Compras → AP */
const BRIDGE_AP_EVENT_TYPES = Object.freeze([
  'PURCHASE_CONFIRMED',
  'PURCHASE_CANCELLED'
]);

/** MFE-07 — Liquidação Financeira */
const SETTLEMENT_EVENT_TYPES = Object.freeze([
  'PAYMENT_SETTLED',
  'PIX_SETTLED',
  'TEF_SETTLED',
  'CASH_SETTLED',
  'CARD_SETTLED',
  'CHECK_SETTLED',
  'BANK_TRANSFER_SETTLED',
  'BOLETO_SETTLED',
  'PAYMENT_REVERSED',
  'PAYMENT_FAILED',
  'LIQUIDACAO_REALIZADA',
  'PIX_LIQUIDADO',
  'TEF_LIQUIDADO',
  'DINHEIRO_LIQUIDADO',
  'CARTAO_LIQUIDADO',
  'CHEQUE_LIQUIDADO',
  'TRANSFERENCIA_LIQUIDADA',
  'BOLETO_LIQUIDADO',
  'LIQUIDACAO_ESTORNADA',
  'LIQUIDACAO_FALHOU'
]);

const FinancialEventTypes = Object.freeze({
  ...OfficialFinancialEventTypes,
  ...LegacyFinancialEventTypes
});

const FINANCIAL_EVENT_TYPE_SET = new Set(Object.values(FinancialEventTypes));

function isEventoCatalogado(type) {
  return FINANCIAL_EVENT_TYPE_SET.has(String(type || ''));
}

function resolverTipoEventoParaPipeline(type) {
  const t = String(type || '');
  if (EVENT_ALIAS_TO_LEGACY[t]) return EVENT_ALIAS_TO_LEGACY[t];
  return t;
}

function isEventoOficial(type) {
  return Object.prototype.hasOwnProperty.call(OfficialFinancialEventTypes, String(type || ''));
}

function isEventoCaixa(type) {
  const t = String(type || '');
  const resolved = resolverTipoEventoParaPipeline(t);
  return CASH_EVENT_TYPES.includes(t) || CASH_EVENT_TYPES.includes(resolved);
}

function isEventoAr(type) {
  const t = String(type || '');
  if (AR_EVENT_TYPES.includes(t) || BRIDGE_AR_EVENT_TYPES.includes(t)) return true;
  const resolved = resolverTipoEventoParaPipeline(t);
  if (t === 'COMMERCIAL_CREDIT_GENERATED' || t === 'COMMERCIAL_CREDIT_USED') return true;
  return AR_EVENT_TYPES.includes(resolved)
    || resolved === 'VENDA_RECEBIDA'
    || resolved === 'VENDA_CANCELADA'
    || resolved === 'PRESTACAO_RECEBIDA';
}

function isEventoAp(type) {
  const t = String(type || '');
  if (AP_EVENT_TYPES.includes(t) || BRIDGE_AP_EVENT_TYPES.includes(t)) return true;
  const resolved = resolverTipoEventoParaPipeline(t);
  if (t === 'PURCHASE_CONFIRMED' || t === 'PURCHASE_CANCELLED') return true;
  return AP_EVENT_TYPES.includes(resolved) || resolved === 'TITULO_AP_CRIADO' || resolved === 'TITULO_AP_BAIXADO';
}

function isEventoSettlement(type) {
  const t = String(type || '');
  if (SETTLEMENT_EVENT_TYPES.includes(t)) return true;
  const resolved = resolverTipoEventoParaPipeline(t);
  return SETTLEMENT_EVENT_TYPES.includes(resolved);
}

module.exports = {
  ...FinancialEventTypes,
  FinancialEventTypes,
  OfficialFinancialEventTypes,
  LegacyFinancialEventTypes,
  EVENT_ALIAS_TO_LEGACY,
  CASH_EVENT_TYPES,
  AR_EVENT_TYPES,
  BRIDGE_AR_EVENT_TYPES,
  AP_EVENT_TYPES,
  BRIDGE_AP_EVENT_TYPES,
  SETTLEMENT_EVENT_TYPES,
  isEventoCatalogado,
  isEventoOficial,
  isEventoCaixa,
  isEventoAr,
  isEventoAp,
  isEventoSettlement,
  resolverTipoEventoParaPipeline,
  FINANCIAL_EVENT_TYPE_SET
};
